### PR TITLE
Spanish from code

### PR DESCRIPTION
**Pull request by deltazerorsan**
Directly translated all strings to Spanish in code.

Still "Settings" and "Help" on the way.

Please @G6EJD tell me if you agree to make public this work when finished.

Roman

### CODE REVIEW

**Comment by deltazerorsan** [comment]
> It would be easier (because I considered this need) to add a new function prefillES and populate that with Spanish and to produce a Spanish help() function that then leaves just a few items that need a translation maybe 4 items of text, that’s all.

Sorry Dave, I don't know the reason I don't receive this answer from you and I send you this pull...

Let me take a look at your proposal, for sure it's better, more flexible, than mine (there are more languages outside)

**Comment by G6EJD** [comment]
I did try to make the code so it was as language independent as possible. It would be possible to add extra fields for the English items but that would make the setup huge, but just adding a language based help and menus would do all of the changes.
Yes publish when done, I’m just trying to help reduce work load in conversion

**Comment by G6EJD** [comment]
Have you given up, if so that’s a shame, it’s good idea, difficult to fully implement but possible to achieve. It’s an interesting problem to solve and your very close to a solution. As I mentioned just one new function prefill_ES and then some scheme to change the input setup fields to Spanish and menu text and that’s all

**Comment by deltazerorsan** [comment]
No! That is the first approach.

I need to fully understand the code and add more TXT_labels for the
interface parts.

My big question is how to decide which prefill to expose and where, some
kind of menu...

For the technical part maybe some #include and #ifdef and putting all the
labels together and only compile one prefill. Thus simplifies where to put
the menu...

**Pull request closed without merging**
